import type { ThemeDefinition } from "vuetify";

export const MAIN_THEME = "mainTheme";
export const mainTheme: ThemeDefinition = {
  dark: false,
  colors: {
    primary: "#4355b9",
    "on-primary": "#ffffff",
    "primary-container": "#dde0ff",
    "on-primary-container": "#000d61",
    secondary: "#5b5d71",
    "on-secondary": "#ffffff",
    "secondary-container": "#e0e1fa",
    "on-secondary-container": "#171a2c",
    tertiary: "#77536d",
    "on-tertiary": "#ffffff",
    "tertiary-container": "#ffd7f3",
    "on-tertiary-container": "#2d1228",
    error: "#ba1b1b",
    "on-error": "#ffffff",
    "error-container": "#ffdad4",
    "on-error-container": "#410001",
    background: "#E3EDF7",
    "on-background": "#1b1b1f",
    surface: "#E3EDF7",
    "on-surface": "#1b1b1f",
    "inverse-surface": "#303034",
    "inverse-on-surface": "#f3f0f5",
    "inverse-primary": "#b9c3ff",
    "surface-variant": "#e3e1ec",
    "on-surface-variant": "#46464f",
    outline: "#46464f",
    shadow: "#000000",
  },
};

export const MAIN_DARK_THEME = "mainDarkTheme";
export const mainDarkTheme: ThemeDefinition = {
  dark: true,
  colors: {
    primary: "#b9c3ff",
    "on-primary": "#08218a",
    "primary-container": "#293ca0",
    "on-primary-container": "#dde0ff",
    secondary: "#c4c5dd",
    "on-secondary": "#2d2f42",
    "secondary-container": "#43465a",
    "on-secondary-container": "#e0e1fa",
    tertiary: "#e5bad7",
    "on-tertiary": "#45263e",
    "tertiary-container": "#5d3c55",
    "on-tertiary-container": "#ffd7f3",
    error: "#ffb4a9",
    "on-error": "#680003",
    "error-container": "#930006",
    "on-error-container": "#ffb4a9",
    background: "#2d2f42",
    "on-background": "#e4e1e6",
    surface: "#1b1b1f",
    "on-surface": "#e4e1e6",
    "inverse-surface": "#e4e1e6",
    "inverse-on-surface": "#303034",
    "inverse-primary": "#4355b9",
    "surface-variant": "#46464f",
    "on-surface-variant": "#46464f",
    outline: "#90909a",
    shadow: "#000000",
  },
};
